### ISSUE TITLE
Request for maintainer status

### ISSUE THREAD

**Issue by movermeyer** [ruby-i18n/ruby-cldr#100]
Hello @tigrish, @camertron, @Korri,

I'm requesting that I be granted "maintainer" status over `ruby-cldr`.

I'm hoping to exercise more control over the codebase than I feel I can as an outside contributor.

As part of my full-time work at Shopify, I maintain an internal library that uses `ruby-cldr` as its source of CLDR data.
As you may have seen, I've committed [many PRs](https://github.com/ruby-i18n/ruby-cldr/pulls?q=is%3Apr+author%3Amovermeyer+) in the last few months, fixing numerous bugs in `ruby-cldr` that were causing incorrect data to be exported. I'm currently the [#3 contributor](https://github.com/ruby-i18n/ruby-cldr/graphs/contributors) to `ruby-cldr`, and at this rate expect to be #1 within a few weeks.

Practically, unless the pattern of contribution changes, I expect that I'll be effectively the sole maintainer.
Of course, I would continue to accept and appreciate any collaboration from you, and will treat your previous contributions with respect.

**I'm hoping that you'll allow me this control over the project, or at the very least, start a discussion around how I can gain such control over time.**

The rest of this issue gives some more details about who I am, and what I hope to do with more control over the future of `ruby-cldr`.

----

### My vision for `ruby-cldr`

I want `ruby-cldr` to be a solid foundational library upon which other i18n libraries in the Ruby/Rails ecosystem can depend to provide easy and accurate access to the latest CLDR data.

Note that I do not wish to expand the scope of `ruby-cldr`. `ruby-cldr` will support the creation of higher-level, end-user APIs by offering easy and accurate access to the upstream CLDR data, but it will not provide those end-user APIs itself.

Examples of potential consumers of `ruby-cldr`'s data:

* [`ruby-i18n/i18n`](https://github.com/ruby-i18n/i18n)
* [`twitter-cldr-rb`](https://github.com/twitter/twitter-cldr-rb)
* `shopify-i18n` (currently internal)

### Some examples of changes I want to make

`ruby-cldr`-specific changes:
* Make (and keep) `ruby-cldr` fully compatible with modern versions of CLDR
* Refactor `export.rb` to be much simpler
* Consistently handle CLDR's `draft` attribute levels

General repos changes:
* Document the scope and invariants of the project, as well as when someone *should* and *shouldn't* use `ruby-cldr`
* Add GitHub PR and Issue templates
* Introduce RuboCop to CI, and fix all linting issues
* Change the default branch from `master` to `main`
* Drop support for end-of-life Ruby versions (?)
* Change CI to GitHub Actions (?)

### My open source CV

I'm not new to the world of open-source maintainership. I'm a maintainer/contributor of several well-used libraries in other ecosystems:

* [`ciso8601`](https://github.com/closeio/ciso8601) a foundational Python library for parsing ISO 8601 timestamps quickly.
  * It's in the top-1000 most downloaded Python libraries 📈
* [Foam](https://foambubble.github.io), a note-taking extension for VSCode.

I also regularly contribute bug reports and bug fixes to all FOSS software I use.

Beyond that, I've been working as a Software Developer for 11 years now. For the past 3, I've been working on i18n systems at Shopify.

### My open source values

* Users should have extreme confidence when upgrading:
  * Maintain backwards compatibility.
    * Breaking changes should be avoided whenever possible.
    * If necessary, should only happen alongside major version bumps, and should have trivial, (preferably automatable) migration paths
  * Keep libraries small in scope, and provide strong invariants that users can always rely on going into the future
  * Follow [the spirit of] [SemVer](https://semver.org/) and [Keep a Changelog](https://keepachangelog.com/)
* Document and support the path to contribution
* Prefer permissive FOSS licenses, but any [FOSS license](https://opensource.org/licenses) is 👌 (`ruby-cldr` is MIT 👍)
  * I include this to express my commitment to "open source", which doesn't include licenses with restrictions on who can use the code

### What I'm asking for

* [`Maintain` or `Admin` role](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization) on `ruby-i18n/ruby-cldr`
  * I figure that I don't necessarily need `Admin` role, though I'll still need someone with `Admin` role to [rename the default branch](https://github.com/ruby-i18n/ruby-cldr/issues/97)

**I'm hoping that you'll allow me this control over the project, or at the very least, start a discussion around how I can gain such control over time.**

**Comment by camertron** [comment]
Hey @movermeyer, thanks for filing this issue.

First off, thanks for all your contributions thus far to ruby-cldr, I've been watching behind the scenes and all your work is appreciated :) I personally don't have any extra time these days (father of 2 young kids, full-time job, etc) so it's been really nice to see progress on the project happening without me. I'm 100% in favor of making you an admin or maintainer of ruby-cldr 😄 

I'm also the maintainer of TwitterCLDR and used to make frequent changes to ruby-cldr, which is why I became a maintainer a few years ago. In fact, ruby-cldr is still one of twitter-cldr-rb's development dependencies. In 2012 when I first started working on TwitterCLDR, ruby-cldr was the easiest way to massage CLDR data into a more usable form. Some of the original date and number formatting code came from ruby-cldr too. Unfortunately I've sort of always thought ruby-cldr wasn't very well-written, and that combined with the evolving needs of TwitterCLDR made me slowly start to rewrite the data import portions. Today, TwitterCLDR uses ruby-cldr to [import](https://github.com/twitter/twitter-cldr-rb/blob/7fee7fdcdd604a8432755efb8e224cc5a6a956f8/lib/twitter_cldr/resources/locales_resources_importer.rb) only a small, ever-shrinking subset of CLDR data. My goal is to eventually stop relying on it entirely.

That said, it would be really cool if ruby-cldr became what you want it to be - "a solid foundational library upon which other i18n libraries in the Ruby/Rails ecosystem can depend." Maybe some day I can delete all the [importers](https://github.com/twitter/twitter-cldr-rb/tree/master/lib/twitter_cldr/resources) from TwitterCLDR and use ruby-cldr instead :)

**Comment by svenfuchs** [comment]
Thank you for your thorough proposal, and all your hard work on this @movermeyer (as well as @camertron and everyone else of course). 

Your ideas for the future course of this library sound very promising. I am looking forward to seeing this code be taken to a new, better shape.

I have just made you a maintainer, please feel free to implement changes as you envision. 

I am going to close this issue. Please let me know if there are any questions, or if there is anything I can help with (also feel free to email me for any private concerns).

**Comment by svenfuchs** [comment]
Changed this to `admin` because https://github.com/ruby-i18n/ruby-cldr/issues/97#issuecomment-991013508 :)

**Comment by tigrish** [comment]
Sorry for being so late to the party, but this is a great move. Welcome @movermeyer! 🥳
