### ISSUE TITLE
Feature request: A way to get the list of locales

### ISSUE THREAD

**Issue by movermeyer** [ruby-i18n/ruby-cldr#59]
It seems that `ruby-cldr` figures out the list of locales by iterating over the filenames:

https://github.com/ruby-i18n/ruby-cldr/blob/e97bdfb53a6301e6b29077f301394860bcced50a/lib/cldr/export/data.rb#L47

This is fine. 

However, users of `ruby-cldr` cannot do this, since the exported directory also contains non-locale directories (ex.`transforms`)

Create a mechanism that allows users to `ruby-cldr` to reliably get the list of locales. Perhaps this could be as simple as generating a `locales.yml` file from `Cldr::Export::Data#locales`.

This would allow `ruby-cldr` to do whatever it would like with the file structure, and give confidence to users that they aren't accidentally including non-locales in their list of regions.

------

Is there an officially supported way to get the list of locales?

**Comment by camertron** [comment]
Hey @movermeyer,

I did a little bit of digging into the CLDR data and couldn't find exactly what you're looking for. I have a hunch that's because locales can be represented in a few different ways. At their most specific, locales specify language, script, and region. For example, English spoken in the US can be represented by `en`, but the full version is really `en-Latn-US`. The CLDR data set contains both `en` _and_ `en-US` (`en` is what's known as a _parent locale_ of `en-US`), but omits the script; really, the script is inferred because US English is only ever written in the Latin alphabet.

In other words, CLDR contains support for all three of these locales: `en`, `en-US`, and `en-Latn-US`. So the question is, should ruby-cldr export a resource that lists all of these locales? I'm not sure that's useful, and it would yield a _very_ long list.

You'd probably be better off determining if a certain locale exists algorithmically by combining [parent locale data](https://unicode.org/reports/tr35/#Parent_Locales) and [likely subtags](https://unicode.org/reports/tr35/#Likely_Subtags). That's essentially what TwitterCLDR does:

```ruby
TwitterCldr::Shared::Locale.parse('en').maximize.to_s  # => "en_Latn_US"
```

Since only a subset of CLDR locales are supported in TwitterCLDR, there's a mechanism for grabbing a supported locale too:

```ruby
```

**Comment by movermeyer** [comment]
> So the question is, should ruby-cldr export a resource that lists all of these locales? I'm not sure that's useful, and it would yield a very long list.

That's actually what I was looking for. I'm looking for a way of knowing all the locales (as output by `Cldr::Export::Data#locales`), without having to parse the directory names and then exclude the non-locale directories like `transforms`.
